
# 配置数据源
hibernate:
  connection:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-b5zx3gjw.cd.tencentcdb.com:10103/cloud_pan_db
    username: root
    password: mysql123
    providerClass: org.hibernate.connection.C3P0ConnectionProvider
  dialect: org.hibernate.dialect.MySQL5Dialect
  c3p0:
    minSize: 5
    maxSize: 10
  hbm2ddl:
    auto: update
  showSql: true
  formatSql: true